# Generated by Django 6.1 on 2026-08-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('record_type', models.CharField(choices=[('TAX_1099', '1099'), ('NONPROFIT_501', '501')], max_length=20)),
                ('is_car_expense', models.BooleanField(default=False)),
                ('receipt_image_url', models.URLField(blank=True, null=True)),
                ('ocr_raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
