# Generated by Django 6.1 on 2026-08-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VaseReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('poc_name', models.CharField(max_length=255)),
                ('poc_facility_name', models.CharField(blank=True, max_length=255)),
                ('poc_phone', models.CharField(blank=True, max_length=30)),
                ('poc_email', models.EmailField(blank=True, max_length=254)),
                ('recipient', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_received'],
            },
        ),
        migrations.CreateModel(
            name='VaseReturned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_returned', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('returned_from', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_returned'],
            },
        ),
    ]
